version: '3.8'

services:
  bot:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://congratz:congratz@db:5432/congratz
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=congratz
      - POSTGRES_PASSWORD=congratz
      - POSTGRES_DB=congratz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U congratz"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 